import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Example dataset
data = {
    "text": [
        "The weather is beautiful today",
        "Humans write stories with emotions and creativity",
        "Artificial intelligence is transforming technology",
        "Researchers are studying new algorithms",
        "This sentence was generated by an AI system",
        "Large language models produce text automatically",
        "AI generated paragraph with structured wording",
        "Machine learning models analyze patterns in data",
        "People communicate thoughts and experiences",
        "This content was created using an AI model"
    ],
    "label": [0,0,0,0,1,1,1,1,0,1]
}

# Convert to dataframe
df = pd.DataFrame(data)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    df["text"], df["label"], test_size=0.25, random_state=42
)

# Convert text to numbers
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Train model
model = LogisticRegression()
model.fit(X_train_vec, y_train)

# Make predictions
predictions = model.predict(X_test_vec)

print("Predictions:", predictions)
print("Actual:", list(y_test))
print("Accuracy:", accuracy_score(y_test, predictions))


# Function to test new text
def predict_text(text):
    vec = vectorizer.transform([text])
    prediction = model.predict(vec)[0]

    if prediction == 0:
        return "Human-written"
    else:
        return "AI-generated"


# Test example
sample_text = "AI systems are rapidly improving every year"
result = predict_text(sample_text)

print("\nSample Text:", sample_text)
print("Prediction:", result)